import React from 'react';
import {
    WifiIcon,
    TvIcon,
    UsersIcon,
    SunIcon,
    ShieldCheckIcon,
    Battery100Icon,
    AdjustmentsVerticalIcon,
    ArchiveBoxIcon,
    ArrowLeftEndOnRectangleIcon,
    ArrowLeftStartOnRectangleIcon,
    BanknotesIcon,
    BellAlertIcon,
    BookOpenIcon,
    BuildingLibraryIcon,
    BuildingOffice2Icon,
    CalendarIcon,
    CameraIcon,
    ChatBubbleLeftIcon,
    CheckIcon,
    CloudIcon,
    ClockIcon,
    ComputerDesktopIcon,
    DocumentIcon,
    EyeIcon,
    FingerPrintIcon,
    FilmIcon,
    FaceSmileIcon,
    ExclamationCircleIcon,
    FireIcon,
    FlagIcon,
    GiftIcon,
    GlobeAltIcon,
    HeartIcon,
    HomeModernIcon,
    IdentificationIcon,
    KeyIcon,
    LifebuoyIcon,
    LightBulbIcon,
    LockClosedIcon,
    LockOpenIcon,
    MapIcon,
    MicrophoneIcon,
    MusicalNoteIcon,
    NewspaperIcon,
    PhoneIcon,
    PhotoIcon,
    PlayIcon,
    PrinterIcon,
    RadioIcon,
    SparklesIcon,
    SpeakerWaveIcon,
    TruckIcon,
    WrenchIcon,
    QuestionMarkCircleIcon // Un ícono por defecto
} from '@heroicons/react/24/outline';

// Un objeto que mapea los nombres de texto a los componentes de ícono
const iconMap = {
    'WifiIcon': WifiIcon,
    'TvIcon': TvIcon,
    'UsersIcon': UsersIcon,
    'SunIcon': SunIcon,
    'ShieldCheckIcon': ShieldCheckIcon,
    'Battery100Icon': Battery100Icon,
    'AdjustmentsVerticalIcon': AdjustmentsVerticalIcon,
    'ArchiveBoxIcon': ArchiveBoxIcon,
    'ArrowLeftEndOnRectangleIcon': ArrowLeftEndOnRectangleIcon,
    'ArrowLeftStartOnRectangleIcon': ArrowLeftStartOnRectangleIcon,
    'BanknotesIcon': BanknotesIcon,
    'BellAlertIcon': BellAlertIcon,
    'BookOpenIcon': BookOpenIcon,
    'BuildingLibraryIcon': BuildingLibraryIcon,
    'BuildingOffice2Icon': BuildingOffice2Icon,
    'CalendarIcon': CalendarIcon,
    'CameraIcon': CameraIcon,
    'ChatBubbleLeftIcon': ChatBubbleLeftIcon,
    'CheckIcon': CheckIcon,
    'CloudIcon': CloudIcon,
    'ClockIcon': ClockIcon,
    'ComputerDesktopIcon': ComputerDesktopIcon,
    'DocumentIcon': DocumentIcon,
    'EyeIcon': EyeIcon,
    'FingerPrintIcon': FingerPrintIcon,
    'FilmIcon': FilmIcon,
    'FaceSmileIcon': FaceSmileIcon,
    'ExclamationCircleIcon': ExclamationCircleIcon,
    'FireIcon': FireIcon,
    'FlagIcon': FlagIcon,
    'GiftIcon': GiftIcon,
    'GlobeAltIcon': GlobeAltIcon,
    'HeartIcon': HeartIcon,
    'HomeModernIcon': HomeModernIcon,
    'IdentificationIcon': IdentificationIcon,
    'KeyIcon': KeyIcon,
    'LifebuoyIcon': LifebuoyIcon,
    'LightBulbIcon': LightBulbIcon,
    'LockClosedIcon': LockClosedIcon,
    'LockOpenIcon': LockOpenIcon,
    'MapIcon': MapIcon,
    'MicrophoneIcon': MicrophoneIcon,
    'MusicalNoteIcon': MusicalNoteIcon,
    'NewspaperIcon': NewspaperIcon,
    'PhoneIcon': PhoneIcon,
    'PhotoIcon': PhotoIcon,
    'PlayIcon': PlayIcon,
    'PrinterIcon': PrinterIcon,
    'RadioIcon': RadioIcon,
    'SparklesIcon': SparklesIcon,
    'SpeakerWaveIcon': SpeakerWaveIcon,
    'TruckIcon': TruckIcon,
    'WrenchIcon': WrenchIcon,
};

// El componente recibe el nombre del ícono como prop
export default function AmenityIcon({ iconName, className = 'h-5 w-5' }) {
    // Busca el componente de ícono en el mapa. Si no lo encuentra, usa el de por defecto.
    const IconComponent = iconMap[iconName] || QuestionMarkCircleIcon;

    return <IconComponent className={className} />;
}
